-- Enable RLS on all tables
ALTER TABLE public."C_CLIENTES" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_CONTRATOS_CLIENTE" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_ESPECIFICACOES_SERVICO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_REQUISICOES_SERVICO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_METRICAS_SOLICITACAO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_FORNECEDORES" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_CONTRATOS_FORNECEDOR" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_PERFIS_RECURSOS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_RECURSOS_FORNECEDOR" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_ORDENS_SERVICO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_ALOCACOES_RECURSOS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."C_APONTAMENTOS_TEMPO" ENABLE ROW LEVEL SECURITY;

-- Create policies to allow all access (can be restricted later)
-- C_CLIENTES
CREATE POLICY "Enable all access for all users" ON public."C_CLIENTES"
FOR ALL USING (true) WITH CHECK (true);

-- C_CONTRATOS_CLIENTE
CREATE POLICY "Enable all access for all users" ON public."C_CONTRATOS_CLIENTE"
FOR ALL USING (true) WITH CHECK (true);

-- C_ESPECIFICACOES_SERVICO
CREATE POLICY "Enable all access for all users" ON public."C_ESPECIFICACOES_SERVICO"
FOR ALL USING (true) WITH CHECK (true);

-- C_REQUISICOES_SERVICO
CREATE POLICY "Enable all access for all users" ON public."C_REQUISICOES_SERVICO"
FOR ALL USING (true) WITH CHECK (true);

-- C_METRICAS_SOLICITACAO
CREATE POLICY "Enable all access for all users" ON public."C_METRICAS_SOLICITACAO"
FOR ALL USING (true) WITH CHECK (true);

-- C_FORNECEDORES
CREATE POLICY "Enable all access for all users" ON public."C_FORNECEDORES"
FOR ALL USING (true) WITH CHECK (true);

-- C_CONTRATOS_FORNECEDOR
CREATE POLICY "Enable all access for all users" ON public."C_CONTRATOS_FORNECEDOR"
FOR ALL USING (true) WITH CHECK (true);

-- C_PERFIS_RECURSOS
CREATE POLICY "Enable all access for all users" ON public."C_PERFIS_RECURSOS"
FOR ALL USING (true) WITH CHECK (true);

-- C_RECURSOS_FORNECEDOR
CREATE POLICY "Enable all access for all users" ON public."C_RECURSOS_FORNECEDOR"
FOR ALL USING (true) WITH CHECK (true);

-- C_ORDENS_SERVICO
CREATE POLICY "Enable all access for all users" ON public."C_ORDENS_SERVICO"
FOR ALL USING (true) WITH CHECK (true);

-- C_ALOCACOES_RECURSOS
CREATE POLICY "Enable all access for all users" ON public."C_ALOCACOES_RECURSOS"
FOR ALL USING (true) WITH CHECK (true);

-- C_APONTAMENTOS_TEMPO
CREATE POLICY "Enable all access for all users" ON public."C_APONTAMENTOS_TEMPO"
FOR ALL USING (true) WITH CHECK (true);

-- C_V_PROJETOS_FINANCEIROS (View)
-- Make the view respect RLS policies of underlying tables
ALTER VIEW public."C_V_PROJETOS_FINANCEIROS" SET (security_invoker = true);
